
---
- name: Add an admin user to hosts
  user:
    name: '{{ admin_user }}'
    groups: sudo
    shell: /bin/bash

- name: Add ssh keys for admin user
  authorized_key:
    user: '{{ admin_user }}'
    key: "{{ lookup('file', '{{ admin_user_key }}') }}"

- name: Add a simple user to remote hosts
  user:
    name: '{{ simple_user }}'
    shell: /bin/bash

- name: Add ssh keys for a simple user
  authorized_key:
    user: '{{ simple_user }}'
    key: "{{ lookup('file', '{{ simple_user_key }}') }}"

- name: copy sudoers for an admin user
  copy:
    dest: "/etc/sudoers.d/{{ admin_user }}"
    mode: 0440
    content: |
      %{{ admin_user }}	ALL=(ALL) NOPASSWD:ALL

- name: copy admin pub-key 
  copy:
    src: '{{ admin_user_key }}'
    dest: '/home/{{ admin_user }}/'
